//******************************************
//Havana Engine API for use in Havana Editor
//******************************************
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif // !WIN32_LEAN_AND_MEAN

#include <Windows.h>
#include "Common.h"

using namespace Havana;

namespace
{
	HMODULE gameCodeDll{ nullptr };
} // anonymous namespace

/// <summary>
/// Load the .dll file generated by the scripts into the Havana Editor
/// for use.
/// </summary>
/// <param name="dllPath">Path of the .dll file.</param>
/// <returns>1 if successful, 0 if not.</returns>
EDITOR_INTERFACE u32 LoadGameCodeDll(const char* dllPath)
{
	if (gameCodeDll) return FALSE; // make sure it's not already loaded

	gameCodeDll = LoadLibraryA(dllPath);
	assert(gameCodeDll);

	return gameCodeDll ? TRUE : FALSE;
}

/// <summary>
/// Unload the .dll file generated by the scripts from the Havana Editor
/// </summary>
/// <param name="dllPath">Path of the .dll file.</param>
/// <returns>1 if successful, 0 if not.</returns>
EDITOR_INTERFACE u32 UnloadGameCodeDll()
{
	if (!gameCodeDll) return FALSE; // make sure it's already loaded
	assert(gameCodeDll);
	
	int result{ FreeLibrary(gameCodeDll) };
	assert(result);
	gameCodeDll = nullptr;
	
	return TRUE;
}