# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Engine_config = debug_x64
  EngineTest_config = debug_x64

else ifeq ($(config),release_x64)
  Engine_config = release_x64
  EngineTest_config = release_x64

else ifeq ($(config),debugeditor_x64)
  Engine_config = debugeditor_x64

else ifeq ($(config),releaseeditor_x64)
  Engine_config = releaseeditor_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Engine EngineTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Engine:
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

EngineTest: Engine
ifneq (,$(EngineTest_config))
	@echo "==== Building EngineTest ($(EngineTest_config)) ===="
	@${MAKE} --no-print-directory -C EngineTest -f Makefile config=$(EngineTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C EngineTest -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo "  debugeditor_x64"
	@echo "  releaseeditor_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Engine"
	@echo "   EngineTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"